-- create DB
CREATE DATABASE Li2S;

-- create USER table
-- insert it in DB selected range
CREATE TABLE USERS(
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    USER_PASS VARCHAR(255) NOT NULL
);

-- create URL table
-- insert it in DB selected range
CREATE TABLE URL(
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT(6),
    FULL_URL VARCHAR(255) NOT NULL,
    SHORT_URL VARCHAR(100) NOT NULL,
    USER_PASS VARCHAR(255) NOT NULL,
    CLICKS INT(6)
);